# Site settings
author: Ron Lynch
title: Tech Overload
header-img: img/home-bg.png
email: lynch.ronald1@gmail.com
copyright_name: Ron Lynch
description: > # this means to ignore newlines until "baseurl:"
  Trying to simplify the static
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Apach317
github_username:  Apach317

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
